//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.02 at 04:16:03 PM TRT 
//


package com.example.FirstTask.service;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tc" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="soyad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dogumyili" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tc",
    "ad",
    "soyad",
    "dogumyili"
})
@XmlRootElement(name = "tcnodogrulaRequest")
public class TcnodogrulaRequest {

    protected long tc;
    @XmlElement(required = true)
    protected String ad;
    @XmlElement(required = true)
    protected String soyad;
    protected int dogumyili;

    /**
     * Gets the value of the tc property.
     * 
     */
    public long getTc() {
        return tc;
    }

    /**
     * Sets the value of the tc property.
     * 
     */
    public void setTc(long value) {
        this.tc = value;
    }

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the soyad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyad() {
        return soyad;
    }

    /**
     * Sets the value of the soyad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyad(String value) {
        this.soyad = value;
    }

    /**
     * Gets the value of the dogumyili property.
     * 
     */
    public int getDogumyili() {
        return dogumyili;
    }

    /**
     * Sets the value of the dogumyili property.
     * 
     */
    public void setDogumyili(int value) {
        this.dogumyili = value;
    }

}
